force-app/main/default/objects/Job_Application__c/Job_Application__c.object-meta.xml
<CustomObject>
    <description>This is junction Object between Job Postings and Applicants (contacts). Each Job Posting can have multiple applications and each applicant can apply to multiple job Postings</description>
    <label>Job Application</label>
    <nameField>
        <displayFormat>JobApp-{0000}</displayFormat>
        <label>Job Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Application__c/fields/Job_Posting__c.field-meta.xml
<CustomField>
    <fullName>Job_Posting__c</fullName>
    <description>Job Posting a master object because, without Job Posting there can be no Job application</description>
    <label>Job Posting</label>
    <referenceTo>Job_Posting__c</referenceTo>
    <relationshipLabel>Job Applications</relationshipLabel>
    <relationshipName>Job_Applications</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Job_Posting__c/Job_Posting__c.object-meta.xml
<CustomObject>
    <description>Its a junction object that relates to Departments(Accounts) and Jobs. Each Job can be posted by multiple departments. That is the reason for junction Object</description>
    <label>Job Posting</label>
    <nameField>
        <displayFormat>JobPos-{0000}</displayFormat>
        <label>Job Posting Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Postings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Posting__c/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Department which created the Job Posting. One Job can be posted by multiple departments</description>
    <label>Department</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Job Postings</relationshipLabel>
    <relationshipName>Job_Postings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/JobApplicationService.cls
/*Rest resource for Single Job Application */
@RestResource(urlMapping='/JobApplicationService/*')
global class JobApplicationService {
	@HttpPost
    global static String createNewJobApplication() {
        String response = '';
        try{
            RestRequest     restRqst = RestContext.request;
            JobApplicationRequest applicationDetails = (JobApplicationRequest) System.JSON.deserialize(restRqst.requestBody.toString(), JobApplicationRequest.class);
            if(applicationDetails.JobPostingId == null || applicationDetails.LastName == null){
                response = 'JobpostingId and LastName are mandatory to process the Application';
            }else{
                Contact applicant = JobApplicationServiceUtility.formContactRecord(applicationDetails);
                insert applicant; 
                
                List<Job_Posting__c> jobPostings = [SELECT Id,Name,Department__r.Name
                                                FROM Job_Posting__c
                                                WHERE Name =:applicationDetails.JobPostingId];
                
                Job_Application__c jobApplication = JobApplicationServiceUtility.formJobApplicationRecord(applicant.Id,jobPostings[0].Id);
                insert jobApplication;
                response = 'Job Application Successfully created with id'+jobApplication.Id;
            }
        }catch(Exception e){
            response = e.getMessage();
        }
        return response;
    }
    
}