force-app/main/default/objects/Job_Application__c/Job_Application__c.object-meta.xml
<CustomObject>
    <description>This is junction Object between Job Postings and Applicants (contacts). Each Job Posting can have multiple applications and each applicant can apply to multiple job Postings</description>
    <label>Job Application</label>
    <nameField>
        <displayFormat>JobApp-{0000}</displayFormat>
        <label>Job Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Application__c/fields/Applicant__c.field-meta.xml
<CustomField>
    <fullName>Applicant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Applicant(Contact) can be related to multiple job applications. Its a not a master as a Job Position sometimes may not have any applicants</description>
    <label>Applicant</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Job Applications</relationshipLabel>
    <relationshipName>Job_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Application_Status__c.field-meta.xml
<CustomField>
    <fullName>Application_Status__c</fullName>
    <description>Application Status. When a Job is filled, Both Jon Status and the application status will be Inactive</description>
    <label>Application Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Review</fullName>
            </value>
            <value>
                <fullName>Recruiter Screening</fullName>
            </value>
            <value>
                <fullName>Hiring Manager</fullName>
            </value>
            <value>
                <fullName>Onsite</fullName>
            </value>
            <value>
                <fullName>Hire</fullName>
            </value>
            <value>
                <fullName>Reject</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Job_Posting__c.field-meta.xml
<CustomField>
    <fullName>Job_Posting__c</fullName>
    <description>Job Posting a master object because, without Job Posting there can be no Job application</description>
    <label>Job Posting</label>
    <referenceTo>Job_Posting__c</referenceTo>
    <relationshipLabel>Job Applications</relationshipLabel>
    <relationshipName>Job_Applications</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Job_Posting__c/Job_Posting__c.object-meta.xml
<CustomObject>
    <description>Its a junction object that relates to Departments(Accounts) and Jobs. Each Job can be posted by multiple departments. That is the reason for junction Object</description>
    <label>Job Posting</label>
    <nameField>
        <displayFormat>JobPos-{0000}</displayFormat>
        <label>Job Posting Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Postings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/JobApplicationServiceUtility.cls
public class JobApplicationServiceUtility {
    public static Contact formContactRecord(JobApplicationRequest application){
        Contact applicant = new Contact(
                                       FirstName = application.FirstName,
                                       LastName = application.LastName,
                                       Email = application.Email,
                                       MailingStreet = application.MailingStreet,
                                       MailingCity = application.MailingCity,
                                       MailingState = application.MailingState,
                                       MailingCountry = application.MailingCountry,
                                       MailingPostalCode = application.MailingPostalCode,
                                       MobilePhone = application.MobilePhone
                                    );
        return applicant;
    }
    public static Job_Application__c formJobApplicationRecord(Id ApplicantId,Id JobPostingId){
     	Job_Application__c jobApplication = new Job_Application__c(
                                                        Applicant__c = ApplicantId,
                                                        Application_Status__c = 'Review',
                                                        Job_Posting__c = JobPostingId
                                                    );   
        return jobApplication;
    }
}