force-app/main/default/objects/Job__c/Job__c.object-meta.xml
<CustomObject>
    <description>Used to capture Job Details</description>
    <label>Job</label>
    <nameField>
        <displayFormat>Job-{0000}</displayFormat>
        <label>Job Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Job__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status indicating whether a Job is active or not. If the value is set to Inactive, Status on the Application object should also be set to Inactive</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Job_Application__c/Job_Application__c.object-meta.xml
<CustomObject>
    <description>This is junction Object between Job Postings and Applicants (contacts). Each Job Posting can have multiple applications and each applicant can apply to multiple job Postings</description>
    <label>Job Application</label>
    <nameField>
        <displayFormat>JobApp-{0000}</displayFormat>
        <label>Job Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Application__c/fields/Application_Status__c.field-meta.xml
<CustomField>
    <fullName>Application_Status__c</fullName>
    <description>Application Status. When a Job is filled, Both Jon Status and the application status will be Inactive</description>
    <label>Application Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Review</fullName>
            </value>
            <value>
                <fullName>Recruiter Screening</fullName>
            </value>
            <value>
                <fullName>Hiring Manager</fullName>
            </value>
            <value>
                <fullName>Onsite</fullName>
            </value>
            <value>
                <fullName>Hire</fullName>
            </value>
            <value>
                <fullName>Reject</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Job_Posting__c.field-meta.xml
<CustomField>
    <fullName>Job_Posting__c</fullName>
    <description>Job Posting a master object because, without Job Posting there can be no Job application</description>
    <label>Job Posting</label>
    <referenceTo>Job_Posting__c</referenceTo>
    <relationshipLabel>Job Applications</relationshipLabel>
    <relationshipName>Job_Applications</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Job_Posting__c/Job_Posting__c.object-meta.xml
<CustomObject>
    <description>Its a junction object that relates to Departments(Accounts) and Jobs. Each Job can be posted by multiple departments. That is the reason for junction Object</description>
    <label>Job Posting</label>
    <nameField>
        <displayFormat>JobPos-{0000}</displayFormat>
        <label>Job Posting Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Postings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Posting__c/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <description>Job to which this Job posting is related to. Its a master detail relationship as a Job Posting cannot exist without a Job record</description>
    <label>Job</label>
    <referenceTo>Job__c</referenceTo>
    <relationshipLabel>Job Postings</relationshipLabel>
    <relationshipName>Job_Postings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Job_Posting__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Job Status</description>
    <formula>TEXT(Job__r.Status__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/JobTriggerHandler.cls
public class JobTriggerHandler {
    public static List<Id> processedJobIds;
    /* @methodName: processJobRecords
     * @description: 1. this method is responsbile for checking if a Job record has been inactivted
     *               2. if a job record is inactivated by recruiter, this method deactivates job applications
     * @parameters: none 
     * @returnType: Map<Id,Job__c> oldJobs (trigger.oldMap), List<Job__c> newJobs(trigger.new)
     */
    public static void processJobRecords(Map<Id,Job__c> oldJobs, List<Job__c> newJobs){
        try{
            List<Id> jobIds = new list<Id>();
            if(null == processedJobIds) processedJobIds = new List<Id>();
            for(Job__c job:newJobs){
                Job__c oldJob = oldJobs.get(job.Id);//get record from oldMap
                boolean hasJobStatusChanged = (job.Status__c != oldJob.Status__c) ? true : false;
                if( hasJobStatusChanged && job.Status__c == 'Inactive'){//check if a Job has been Inactivated
                    if(!processedJobIds.contains(job.Id)){//Logic to avoid recursion
                   		jobIds.add(job.Id); 
                        processedJobIds.add(job.Id);
                    }
                }
            }
            if(!jobIds.isEmpty()){
                //Call Method to Query Job Application Records
               List<Job_Application__c> jobApplications = queryJobApplications(jobIds);
               if(!jobApplications.isEmpty()){
                   for(Job_Application__c jobApp:jobApplications) {
                       jobApp.Application_Status__c = 'Inactive';//Deactivate Job Applications
                   }
                   //Call Method to update JobApplications
                   deactivateJobApplications(jobApplications);
               }
            }
        }catch(Exception e){
            //Error Handling mechanism can be implemented by creating a custom Object called Error Logger 
        }
    }
    /* @methodName: queryJobApplications
     * @description: 1. Query Job Application records 
     * @parameters: List<Id> jobIds 
     * @returnType: List<Job_Application__c>
     */
    public static List<Job_Application__c> queryJobApplications(List<Id> jobIds){
        List<Job_Application__c> jobApplications =  new List<Job_Application__c>();
        jobApplications = [SELECT Id,Application_Status__c,Job_Posting__r.Job__c
                           FROM Job_Application__c
                           WHERE Job_Posting__r.Job__c IN:jobIds AND 
                                 Application_Status__c !='Inactive'];
        return jobApplications; 
    }
    /* @methodName: deactivateJobApplications
     * @description: 1. Update Job Application records with Application Status value as 'Inactive'
     * @parameters: List<Job_Application__c> jobApplications
     * @returnType: none
     */
    public static void deactivateJobApplications(List<Job_Application__c> jobApplications){
        Database.SaveResult[] srList = Database.update(jobApplications, false); 
        for (Database.SaveResult sr : srList) {
            if (sr.isSuccess()) {
                // Operation was successful, so get the ID of the record that was processed
                System.debug('Successfully updated jobApplication. jobApplication ID: ' + sr.getId());
            }
            else {
                // Operation failed, so get all errors                
                for(Database.Error err : sr.getErrors()) {
                    System.debug('The following error has occurred.');                    
                    System.debug(err.getStatusCode() + ': ' + err.getMessage());
                    System.debug('jobApplication fields that affected this error: ' + err.getFields());
                }
            }
	   }
    }
}