force-app/main/default/objects/Job__c/Job__c.object-meta.xml
<CustomObject>
    <description>Used to capture Job Details</description>
    <label>Job</label>
    <nameField>
        <displayFormat>Job-{0000}</displayFormat>
        <label>Job Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Job__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status indicating whether a Job is active or not. If the value is set to Inactive, Status on the Application object should also be set to Inactive</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Job_Application__c/Job_Application__c.object-meta.xml
<CustomObject>
    <description>This is junction Object between Job Postings and Applicants (contacts). Each Job Posting can have multiple applications and each applicant can apply to multiple job Postings</description>
    <label>Job Application</label>
    <nameField>
        <displayFormat>JobApp-{0000}</displayFormat>
        <label>Job Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Application__c/fields/Application_Status__c.field-meta.xml
<CustomField>
    <fullName>Application_Status__c</fullName>
    <description>Application Status. When a Job is filled, Both Jon Status and the application status will be Inactive</description>
    <label>Application Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Review</fullName>
            </value>
            <value>
                <fullName>Recruiter Screening</fullName>
            </value>
            <value>
                <fullName>Hiring Manager</fullName>
            </value>
            <value>
                <fullName>Onsite</fullName>
            </value>
            <value>
                <fullName>Hire</fullName>
            </value>
            <value>
                <fullName>Reject</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Job_Posting__c.field-meta.xml
<CustomField>
    <fullName>Job_Posting__c</fullName>
    <description>Job Posting a master object because, without Job Posting there can be no Job application</description>
    <label>Job Posting</label>
    <referenceTo>Job_Posting__c</referenceTo>
    <relationshipLabel>Job Applications</relationshipLabel>
    <relationshipName>Job_Applications</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Job_Posting__c/Job_Posting__c.object-meta.xml
<CustomObject>
    <description>Its a junction object that relates to Departments(Accounts) and Jobs. Each Job can be posted by multiple departments. That is the reason for junction Object</description>
    <label>Job Posting</label>
    <nameField>
        <displayFormat>JobPos-{0000}</displayFormat>
        <label>Job Posting Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Postings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Posting__c/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <description>Job to which this Job posting is related to. Its a master detail relationship as a Job Posting cannot exist without a Job record</description>
    <label>Job</label>
    <referenceTo>Job__c</referenceTo>
    <relationshipLabel>Job Postings</relationshipLabel>
    <relationshipName>Job_Postings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Job_Posting__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Job Status</description>
    <formula>TEXT(Job__r.Status__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/JobtriggerTest.cls
@isTest
public class JobtriggerTest {
    @isTest static void testDeActivateJob_To_VerifyApplicationsAlsoDeActivated(){
        List<Account> departments = TestDataFactory.createDepartments(1);
        List<Job__c> jobs = TestDataFactory.createJobs(1);
        List<Job_Posting__c> jobPostings = TestDataFactory.createJobPostings(jobs, departments);
        List<Contact> applicants = TestDataFactory.createApplicants(1);
        List<Job_Application__c> jobApplications = TestDataFactory.createJobApplications(jobPostings, applicants); 
        Test.startTest();
            jobs[0].Status__c = 'Inactive';
            update jobs; 
        Test.stopTest();
        
        List<Job_Application__c> applications = [select Id,Application_Status__c from Job_Application__c
                                                WHERE Application_Status__c = 'Inactive'];
        System.assertEquals(1, applications.size());
    }
}