force-app/main/default/objects/Job__c/Job__c.object-meta.xml
<CustomObject>
    <description>Used to capture Job Details</description>
    <label>Job</label>
    <nameField>
        <displayFormat>Job-{0000}</displayFormat>
        <label>Job Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Application__c/Job_Application__c.object-meta.xml
<CustomObject>
    <description>This is junction Object between Job Postings and Applicants (contacts). Each Job Posting can have multiple applications and each applicant can apply to multiple job Postings</description>
    <label>Job Application</label>
    <nameField>
        <displayFormat>JobApp-{0000}</displayFormat>
        <label>Job Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Application__c/fields/Job_Posting__c.field-meta.xml
<CustomField>
    <fullName>Job_Posting__c</fullName>
    <description>Job Posting a master object because, without Job Posting there can be no Job application</description>
    <label>Job Posting</label>
    <referenceTo>Job_Posting__c</referenceTo>
    <relationshipLabel>Job Applications</relationshipLabel>
    <relationshipName>Job_Applications</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Job_Posting__c/Job_Posting__c.object-meta.xml
<CustomObject>
    <description>Its a junction object that relates to Departments(Accounts) and Jobs. Each Job can be posted by multiple departments. That is the reason for junction Object</description>
    <label>Job Posting</label>
    <nameField>
        <displayFormat>JobPos-{0000}</displayFormat>
        <label>Job Posting Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Postings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Posting__c/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <description>Job to which this Job posting is related to. Its a master detail relationship as a Job Posting cannot exist without a Job record</description>
    <label>Job</label>
    <referenceTo>Job__c</referenceTo>
    <relationshipLabel>Job Postings</relationshipLabel>
    <relationshipName>Job_Postings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/JobApplicationServiceTest.cls
@isTest
public class JobApplicationServiceTest {
    @isTest static void testJobApplicationServiceWhichCreatesSingleApplicationInSF(){
        List<Account> departments = TestDataFactory.createDepartments(1);
        List<Job__c> jobs = TestDataFactory.createJobs(1);
        List<Job_Posting__c> jobPostings = TestDataFactory.createJobPostings(jobs, departments);
        jobPostings = [select Id,Name from Job_Posting__c];
        JobApplicationRequest appReq = new JobApplicationRequest();
        appReq.FirstName = 'Amrutha';
        appReq.LastName = 'Achukatla';
        appReq.Email = 'AMrutha474@gmail.com';
        appReq.MobilePhone = '9897652341';
        appReq.JobPostingId = jobPostings[0].Name;
        appReq.MailingStreet = 'testStreet';
        appReq.MailingCity = 'testCity';
        appreq.MailingCountry = 'USA';
        appReq.MailingState = 'NC';
        appReq.MailingPostalCode = '27513';
        
        String myJSON = JSON.serialize(appReq); 
        RestRequest request = new RestRequest(); 
        request.requestUri ='https://bandwidth-dev-ed.my.salesforce.com//services/apexrest/JobApplicationService/';
        request.httpMethod = 'POST';
		request.requestBody = Blob.valueof(myJSON);
        RestContext.request = request;
        Test.startTest();
        	JobApplicationService.createNewJobApplication();
        Test.stopTest();
        List<Job_Application__c> JobApps = [select Id from Job_Application__c];
        System.assertEquals(1, JobApps.size());
        
    }
}